### PR TITLE
added basic travis setup

### PR DESCRIPTION
**Pull request by jameslamb**
I tried to add some CI support tonight. Let's see if it works

### CODE REVIEW

**Comment by jameslamb** [comment]
This won't get picked up by Travis until we merge. But I have been testing on my fork (not working yet): https://travis-ci.org/jameslamb/cran-server/jobs/408774875

**Comment by jameslamb** [comment]
oh it was broken because `pythom` isn't a thing

image

**Comment by jameslamb** [comment]
oh hey I got it to pick up the PR!

**Comment by jameslamb** [comment]
it's currently only building for Python 3.6. I didn't realize the note in the README about the py3 floor.

Since this is getting run in a container anyway, I vote we just test on 3.6

**Comment by jameslamb** [comment]
HEY LOOK IT WORKED!

**Comment by ntdef** [comment]
awesome! thanks for setting this up

**Pull request merged**
